name: shieldx
description: "A secure password manager that stores your passwords with
  military-grade encryption."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  animations: ^2.1.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  encrypt: ^5.0.3
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.0
  toastification: ^3.0.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/fonts/google/
    - assets/fonts/inter/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf

    - family: Google Sans Flex
      fonts:
        - asset: assets/fonts/google/GoogleSansFlex_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/google/GoogleSansFlex_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/google/GoogleSansFlex_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/google/GoogleSansFlex_24pt-Regular.ttf
